[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://hrms-30g6.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/hubs/*"
  to = "https://hrms-30g6.onrender.com/hubs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
