export interface Theme {
  name: string;
  displayName: string;
  primary: string;
  primaryLight: string;
  primaryDark: string;
  secondary: string;
  accent: string;
  success: string;
  warning: string;
  danger: string;
  info: string;
  bg: string;
  surface: string;
  surfaceHover: string;
  text: string;
  textSecondary: string;
  border: string;
  borderLight: string;
  sidebarBg: string;
  sidebarText: string;
  sidebarHover: string;
  sidebarActive: string;
  headerBg: string;
  headerBorder: string;
  cardBg: string;
  inputBg: string;
  inputBorder: string;
  isDark: boolean;
}

export const THEMES: Theme[] = [
  {
    name: 'default',
    displayName: 'Indigo (Default)',
    primary: '#4F46E5',
    primaryLight: '#818CF8',
    primaryDark: '#4338CA',
    secondary: '#7C3AED',
    accent: '#8B5CF6',
    success: '#059669',
    warning: '#D97706',
    danger: '#DC2626',
    info: '#2563EB',
    bg: '#F9FAFB',
    surface: '#FFFFFF',
    surfaceHover: '#F3F4F6',
    text: '#1F2937',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    sidebarBg: '#FFFFFF',
    sidebarText: '#374151',
    sidebarHover: '#F3F4F6',
    sidebarActive: '#EEF2FF',
    headerBg: '#FFFFFF',
    headerBorder: '#E5E7EB',
    cardBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    inputBorder: '#D1D5DB',
    isDark: false,
  },
  {
    name: 'dark',
    displayName: 'Dark',
    primary: '#818CF8',
    primaryLight: '#A5B4FC',
    primaryDark: '#6366F1',
    secondary: '#A78BFA',
    accent: '#C4B5FD',
    success: '#34D399',
    warning: '#FBBF24',
    danger: '#F87171',
    info: '#60A5FA',
    bg: '#111827',
    surface: '#1F2937',
    surfaceHover: '#374151',
    text: '#F9FAFB',
    textSecondary: '#9CA3AF',
    border: '#374151',
    borderLight: '#4B5563',
    sidebarBg: '#1F2937',
    sidebarText: '#D1D5DB',
    sidebarHover: '#374151',
    sidebarActive: '#312E81',
    headerBg: '#1F2937',
    headerBorder: '#374151',
    cardBg: '#1F2937',
    inputBg: '#374151',
    inputBorder: '#4B5563',
    isDark: true,
  },
  {
    name: 'blue',
    displayName: 'Ocean Blue',
    primary: '#2563EB',
    primaryLight: '#60A5FA',
    primaryDark: '#1D4ED8',
    secondary: '#0891B2',
    accent: '#06B6D4',
    success: '#059669',
    warning: '#D97706',
    danger: '#DC2626',
    info: '#7C3AED',
    bg: '#F0F9FF',
    surface: '#FFFFFF',
    surfaceHover: '#EFF6FF',
    text: '#1E293B',
    textSecondary: '#64748B',
    border: '#CBD5E1',
    borderLight: '#E2E8F0',
    sidebarBg: '#FFFFFF',
    sidebarText: '#334155',
    sidebarHover: '#EFF6FF',
    sidebarActive: '#DBEAFE',
    headerBg: '#FFFFFF',
    headerBorder: '#CBD5E1',
    cardBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    inputBorder: '#94A3B8',
    isDark: false,
  },
  {
    name: 'green',
    displayName: 'Forest Green',
    primary: '#059669',
    primaryLight: '#34D399',
    primaryDark: '#047857',
    secondary: '#0D9488',
    accent: '#14B8A6',
    success: '#16A34A',
    warning: '#CA8A04',
    danger: '#DC2626',
    info: '#2563EB',
    bg: '#F0FDF4',
    surface: '#FFFFFF',
    surfaceHover: '#F0FDF4',
    text: '#14532D',
    textSecondary: '#576E5E',
    border: '#BBF7D0',
    borderLight: '#DCFCE7',
    sidebarBg: '#FFFFFF',
    sidebarText: '#365314',
    sidebarHover: '#F0FDF4',
    sidebarActive: '#DCFCE7',
    headerBg: '#FFFFFF',
    headerBorder: '#BBF7D0',
    cardBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    inputBorder: '#86EFAC',
    isDark: false,
  },
  {
    name: 'purple',
    displayName: 'Royal Purple',
    primary: '#7C3AED',
    primaryLight: '#A78BFA',
    primaryDark: '#6D28D9',
    secondary: '#C026D3',
    accent: '#D946EF',
    success: '#059669',
    warning: '#D97706',
    danger: '#DC2626',
    info: '#2563EB',
    bg: '#FAF5FF',
    surface: '#FFFFFF',
    surfaceHover: '#F5F3FF',
    text: '#3B0764',
    textSecondary: '#6B7280',
    border: '#E9D5FF',
    borderLight: '#F3E8FF',
    sidebarBg: '#FFFFFF',
    sidebarText: '#581C87',
    sidebarHover: '#F5F3FF',
    sidebarActive: '#F3E8FF',
    headerBg: '#FFFFFF',
    headerBorder: '#E9D5FF',
    cardBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    inputBorder: '#C4B5FD',
    isDark: false,
  },
  {
    name: 'rose',
    displayName: 'Rose Pink',
    primary: '#E11D48',
    primaryLight: '#FB7185',
    primaryDark: '#BE123C',
    secondary: '#DB2777',
    accent: '#EC4899',
    success: '#059669',
    warning: '#D97706',
    danger: '#B91C1C',
    info: '#2563EB',
    bg: '#FFF1F2',
    surface: '#FFFFFF',
    surfaceHover: '#FFF1F2',
    text: '#881337',
    textSecondary: '#9F1239',
    border: '#FECDD3',
    borderLight: '#FFE4E6',
    sidebarBg: '#FFFFFF',
    sidebarText: '#9F1239',
    sidebarHover: '#FFF1F2',
    sidebarActive: '#FFE4E6',
    headerBg: '#FFFFFF',
    headerBorder: '#FECDD3',
    cardBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    inputBorder: '#FDA4AF',
    isDark: false,
  },
];
